[project]
name = "api-base"
version = "0.1.0"
description = "API service base"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "dishka>=1.7.2",
    "fastapi>=0.137.2",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "mypy>=1.16.1",
    "orjson>=3.11.8",
    "pydantic-settings>=2.15.0",
    "pydantic>=2.12.5",
    "pytest-asyncio>=1.0.0",
    "tenacity>=9.1.4",
    "uvicorn>=0.34.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
api-base = "src.entrypoint.main:main"

[tool.ty.src]
exclude = []
include = ["src/", "main.py"]
