from typing import Any, Protocol, runtime_checkable

from httpx import AsyncClient, Response


@runtime_checkable
class IBaseClient(Protocol):
    base_url: str
    token: str | None
    session: AsyncClient | None
    headers: dict | None
    params: dict | None

    @classmethod
    def create(cls, **kwargs: Any) -> "IBaseClient": ...

    async def patch(self, url: str, json: dict, **kwargs: Any) -> Response: ...
    async def put(self, url: str, json: dict, **kwargs: Any) -> Response: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, json: dict, **kwargs: Any) -> Response: ...
    async def delete(self, url: str, **kwargs: Any) -> Response: ...
    async def close(self) -> None: ...
    def build_path(self, path: str) -> str: ...
